@startuml
class UserInterface {
    + UserInterface(powerButton:IButton, timeButton:IButton, startCancelButton:IButton, door:IDoor, display:IDisplay, light:ILight, cooker:ICookController)
    + OnPowerPressed(sender:object, e:EventArgs) : void
    + OnTimePressed(sender:object, e:EventArgs) : void
    + OnStartCancelPressed(sender:object, e:EventArgs) : void
    + OnDoorOpened(sender:object, e:EventArgs) : void
    + OnDoorClosed(sender:object, e:EventArgs) : void
    + CookingIsDone() : void
}

@enduml
